[build]
  publish = "dist"
  command = "npm run build"

[build.environment]
  NODE_VERSION = "18"

# Serve static assets directly (higher priority)
[[redirects]]
  from = "/ielts/assets/*"
  to = "/ielts/assets/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/ielts/*.svg"
  to = "/ielts/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/ielts/*.png"
  to = "/ielts/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/ielts/*.webp"
  to = "/ielts/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/ielts/*.jpg"
  to = "/ielts/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/ielts/*.jpeg"
  to = "/ielts/:splat"
  status = 200
  force = true

# SPA routing for HTML pages (lower priority)
[[redirects]]
  from = "/ielts/*"
  to = "/ielts/index.html"
  status = 200
  force = false

[[redirects]]
  from = "/gre/*"
  to = "/gre/index.html"
  status = 200
  force = false

[[redirects]]
  from = "/gmat/*"
  to = "/gmat/index.html"
  status = 200
  force = false

# Fallback for all other routes
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Headers for security and performance
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Form handling
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200
