[build]
  publish = "dist"
  command = "./build.sh"
  base = "."

[build.environment]
  NODE_VERSION = "18"

# Static HTML deployment - serves static HTML from dist directory

# Redirect root to IELTS Chennai app (main app)
[[redirects]]
  from = "/"
  to = "/ielts-chennai/"
  status = 200

# Specific redirects for each app
[[redirects]]
  from = "/ielts-chennai"
  to = "/ielts-chennai/"
  status = 200

[[redirects]]
  from = "/ielts-vadodara"
  to = "/ielts-vadodara/"
  status = 200

[[redirects]]
  from = "/ielts-online"
  to = "/ielts-online/"
  status = 200

[[redirects]]
  from = "/gre"
  to = "/"
  status = 301

[[redirects]]
  from = "/gmat"
  to = "/gmat/"
  status = 200

[[redirects]]
  from = "/dubai"
  to = "/dubai/"
  status = 200

[[redirects]]
  from = "/gre"
  to = "/"
  status = 301

[[redirects]]
  from = "/us"
  to = "/us/"
  status = 200

[[redirects]]
  from = "/uk"
  to = "/uk/"
  status = 200

[[redirects]]
  from = "/sat"
  to = "/sat/"
  status = 200

[[redirects]]
  from = "/canada"
  to = "/canada/"
  status = 200

# Catch-all redirect for SPA routing within each app
[[redirects]]
  from = "/ielts-chennai/*"
  to = "/ielts-chennai/index.html"
  status = 200

[[redirects]]
  from = "/ielts-vadodara/*"
  to = "/ielts-vadodara/index.html"
  status = 200

[[redirects]]
  from = "/ielts-online/*"
  to = "/ielts-online/index.html"
  status = 200

[[redirects]]
  from = "/gre/*"
  to = "/"
  status = 301

[[redirects]]
  from = "/gmat/*"
  to = "/gmat/index.html"
  status = 200

[[redirects]]
  from = "/dubai/*"
  to = "/dubai/index.html"
  status = 200

[[redirects]]
  from = "/gre/*"
  to = "/"
  status = 301

[[redirects]]
  from = "/us/*"
  to = "/us/index.html"
  status = 200

[[redirects]]
  from = "/uk/thank-you"
  to = "/uk/thank-you.html"
  status = 200

[[redirects]]
  from = "/uk/*"
  to = "/uk/index.html"
  status = 200

# Thank you page redirects
[[redirects]]
  from = "/ielts-chennai/thank-you"
  to = "/ielts-chennai/thank-you.html"
  status = 200

[[redirects]]
  from = "/ielts-vadodara/thank-you"
  to = "/ielts-vadodara/thank-you.html"
  status = 200

[[redirects]]
  from = "/ielts-online/thank-you"
  to = "/ielts-online/thank-you.html"
  status = 200

[[redirects]]
  from = "/us/thank-you"
  to = "/us/thank-you.html"
  status = 200

[[redirects]]
  from = "/sat/thank-you"
  to = "/sat/thank-you.html"
  status = 200

[[redirects]]
  from = "/canada/thank-you"
  to = "/canada/thank-you.html"
  status = 200

[[redirects]]
  from = "/sat/*"
  to = "/sat/index.html"
  status = 200

[[redirects]]
  from = "/canada/*"
  to = "/canada/index.html"
  status = 200

# Headers for security and performance
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Form handling
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

